### PR TITLE
Bug: InputValue Handling 

### LINKED ISSUE #37: InputValue Handling
## Describe the bug

This bugs were mentioned by @Arol15 

> 1. clear the input field after a message has been successfully posted;
> 2. fix TS warning for this line: const text = form.get("message").valueOf(); - text can be null;
> 3. make input field required or disable send message button if no input entered;

## Steps to reproduce

1. Go to a chat room.
2. Submit the empty string. You can see the party server received the empty text
3. Put any message in the input field. The message stays after submission.

## Expected behavior
- Users should not be able to submit an empty text. 
- Input field should be cleared after submission.

## Screenshots

input-demo

## Possible Solution

Right now, we use the FormData to get the input value
``` 
const form = new FormData(event.target as HTMLFormElement);
          const text = form.get("message").valueOf();
```
I think it's better to utilize useState for inputValue to reset the input field after submission.

I would add `const [inputValue, setInputValue] = useState("");` to the line 15, 
add `value={inputValue}
              onChange={(e) => {
                setInputValue(e.target.value);
              }}` to the input element at the line 52,
 and modify form onSubmit like this 
```
<form
        className="mt-2 flex flex-col gap-4"
        onSubmit={(event) => {
          if (inputValue !== "") {
            socket.send(JSON.stringify({ user: username, text: inputValue }));
            setInputValue("");}
          event.preventDefault();
        }}
      >
```

### PR DESCRIPTION
**Pull request by Arol15**
## Description

This PR enhances InputValue handling with the following improvements:

 - Prevents users from submitting empty text.
 - Clears the input field after submission for a better user experience.
 - Fixes TS warning by using the chaining operator for the text field. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] 📦 Chore
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #37

## Mobile & Desktop Screenshots/Recordings

https://github.com/nickytonline/astro-partykit-starter/assets/25575320/1c37eb13-6042-473b-9a10-05c3c3c8b13a

## Steps to QA

1. Go to a chat room.
2. Attempt to send a message without entering any text. The message 'Please fill out this field' should appear.
3. After sending or submitting a message, observe that the input field is cleared.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📜 CONTRIBUTING.md
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

gif

### CODE REVIEW

**Review by Satoshi-Sh — APPROVED** [review]
Worked fine as expected. 

I didn't know event.target.reset() reflected to the form right away. I thought it should be rerendered.

**Comment by nickytonline** [comment]
> Worked fine as expected.
> 
> I didn't know event.target.reset() reflected to the form right away. I thought it should be rerendered.

These are web primitives that have existed for a long long time. It does [reset the form](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset), but it will reset the form to their initial values. In our case since the initial value was empty, that's why it clears it.

**Comment by nickytonline** [comment]
@Arol15, mind adding a short PR description? Thanks for the QA steps!

**Comment by Arol15** [comment]
> @Arol15, mind adding a short PR description? Thanks for the QA steps!

Yes! Sorry, I didn't finish it yet. Once I'm ready, I'll make it available for review.

File: src/components/Party.tsx [hunk 1]
```diff
@@ -50,6 +50,7 @@ export const Party = ({ username, roomId }: PartyProps) => {
               className="border border-gray-400 rounded p-2"
               name="message"
               type="text"
+              required
```
Comment (Arol15) [inline src/components/Party.tsx:53]: I'm not sure if this is the desired approach. Usually, we are used to a different chat experience. Perhaps disabling the 'Send Message' button or preventing message posting when pressing 'Enter' would be preferable?"

Comment (Satoshi-Sh) [reply src/components/Party.tsx:53]: Sorry @Arol15, I didn't notice it was a draft. 

I feel it's fine with the current solution about the blank input.

**Review by Satoshi-Sh — APPROVED** [review]
Looks great!! Thanks for your contribution.

File: src/components/Party.tsx (hunk 1 above)
Comment (nickytonline) [reply src/components/Party.tsx:53]: Required is all good. It'll do the job. 🫡

File: src/components/Party.tsx [hunk 2]
```diff
@@ -37,10 +37,10 @@ export const Party = ({ username, roomId }: PartyProps) => {
         className="mt-2 flex flex-col gap-4"
         onSubmit={(event) => {
           const form = new FormData(event.target as HTMLFormElement);
-          const text = form.get("message").valueOf();
-
+          const text = form.get("message")?.valueOf();
           socket.send(JSON.stringify({ user: username, text }));
           event.preventDefault();
+          (event.target as HTMLFormElement).reset();
```
Comment (nickytonline) [inline src/components/Party.tsx:43]: refactor (blocking) use the form variable defined above in the function.

```suggestion
          form.reset();
```

**Review by nickytonline — CHANGES_REQUESTED** [review]
One small change request.

File: src/components/Party.tsx (hunk 2 above)
Comment (Arol15) [reply src/components/Party.tsx:43]: Thanks, Nick! I've tried doing it but I'm getting a TS error: `Property 'reset' does not exist on type 'FormData'. Did you mean 'set'?ts(2551)`. 
According to chatGPT, this error is because the reset method is not a part of the FormData interface in TypeScript. The reset method is associated with the HTMLFormElement interface. 
That's why we need to cast `eventTarget` as `HTMLFormElement` so TS knows that it's a form element and we can use `reset()`.

Comment (nickytonline) [reply src/components/Party.tsx:43]: Oops! You're right! I'm on mobile. 😅 That's the form data, not the form. You could create a form variable before the form data and use it for the form data and then for the reset.

Comment (Arol15) [reply src/components/Party.tsx:43]: 😅
do you mean like this: 
```
onSubmit={(event) => {
          const formElement = event.target as HTMLFormElement;
          const form = new FormData(formElement);
          const text = form.get("message")?.valueOf();
          socket.send(JSON.stringify({ user: username, text }));
          event.preventDefault();
          formElement.reset();
        }}
```

or we could do this:

```
onSubmit={(event) => {
  const formElement = event.target as HTMLFormElement;
  const text = formElement.message.value; 
  socket.send(JSON.stringify({ user: username, text }));
  event.preventDefault();

  formElement.reset();
}};
```

Comment (nickytonline) [reply src/components/Party.tsx:43]: Either works. I'd just put the event.preventDefault() at the end, but it's not blocking getting this PR merged.

Comment (Arol15) [reply src/components/Party.tsx]: I just realized that we are not using `event.preventDefault()` at the beginning of the form submission handler. I believe I've always used it as my first line to prevent the default form submission behavior. why do we prefer using it at the end in this case?

Comment (nickytonline) [reply src/components/Party.tsx]: It can be at the beginning or the end. The reason for the end is for progressive enhancement.

Say there are JavaScript errors, the form won't be able to submit, but it doesn't really apply in our case because we don't have a form submission being sent back doing a full form , we're just sending it over websockets (partykit).

[Austin Gil explains this well in the live stream we did](https://youtu.be/cIkQ_4CEUlA?t=2983).

Comment (Arol15) [reply src/components/Party.tsx]: Makes sense! Thanks, Nick! Will def watch the video.

Comment (Arol15) [reply src/components/Party.tsx]: This video deserved a subscribe from me! :D I'm your 423rd subscriber, Nick! 🎉 will leave it here for records haha 
Screenshot 2024-01-23 at 8 21 34 PM

**Comment by Arol15** [comment]
is there anything else we would like to do in this PR?

**Review by nickytonline — APPROVED** [review]
Thanks @Arol15! :shipit:

**Review by Satoshi-Sh — APPROVED** [review]
Thanks!!
